version: '3.7'
services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: mtt_lms
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - './mysql-data:/var/lib/mysql'
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"